# WARNING - Generated by {fusen} from dev/flat_nimble.Rmd: do not edit by hand # nolint: line_length_linter.


test_that("Gro_writenimblecode errors", {
  expect_error(
   Gro_writenimblecode(params = c('z0', 'zinf', 'gamma'), 
                    model = "for (j in 1:N){{
       logz[j] ~dnorm(zinf[IND[j]] * (1 - exp(- gamma[IND[j]] * logx[j])), sigma_res)}}"
),
    regexp = "z0 not included in the likelihood of the model")
     expect_error(
   Gro_writenimblecode(params = c('z0', 'zinf', 'gamma'), 
                       random = "a",
                    model = "for (j in 1:N){{
       logz[j] ~dnorm(zinf[IND[j]] +z0 +* (1 - exp(- gamma[IND[j]] * logx[j])), sigma_res)}}"),
    regexp = "lements 1 of random %in% params are not true")
})

test_that("Gro_writenimblecode works", {
 
  a =Gro_writenimblecode(params = c('z0', 'zinf', 'gamma'), 
                    model = "for (j in 1:N){{
       logz[j] ~dnorm(z0[IND[j]] + zinf[IND[j]] * (1 - exp(- gamma[IND[j]] * logx[j])), sigma_res)}}",
                    random = "gamma",
                    maxval = list(z0 = 5), 
                    minval= list(z0 = 0, zinf = 0, gamma = 0)
)
  expect_equal(
    a%>%as.character(),
               c("sigma_res ~ dunif(0, 150)", "mu_z0 ~ dunif(0, 5)", 
                 "for (i in 1:Nind) {\n    z0[i] <- mu_z0\n}",
                 "mu_zinf ~ dunif(0, 1000)",
                 "for (i in 1:Nind) {\n    zinf[i] <- mu_zinf\n}", 
                 "mu_gamma ~ dunif(0, 1000)", 
                 "sigma_gamma ~ dunif(0, 150)", 
                 "for (i in 1:Nind) {\n    gamma[i] ~ dnorm(mu_gamma, sd = sigma_gamma)\n}", 
                 "for (j in 1:N) {\n    {\n        logz[j] ~ dnorm(z0[IND[j]] + zinf[IND[j]] * (1 - exp(-gamma[IND[j]] * logx[j])), sigma_res)\n    }\n}" ))
})



