# WARNING - Generated by {fusen} from dev/flat_main.Rmd: do not edit by hand # nolint: line_length_linter.

Age <- sample(c(0:10), 1000, replace = TRUE)
MeasurementValue <- exp(0.2+15 * (1 - exp(-(0.1) * log(Age+1)))+ rnorm(1000,0,0.01))-1 
AnimalAnonID <- sample(c(0:20), 100, replace = TRUE)
dat = data.frame(Age = Age, MeasurementValue = MeasurementValue, 
                 AnimalAnonID = AnimalAnonID, MeasurementType = "Live Weight")

test_that(
  "Gro_analysis works",
  { 
    out = Gro_analysis(dat, all_mods  = c("vonbertalanffy"),
                       random = list(vonbertalanffy = c("z0", "z0, zinf")),
                       run = list(nit = 100, nburnin = 10, nthin = 1, nch = 1))
    
    expect_named(out,c( "model", "wAIC_tab"))
    expect_named(out$wAIC_tab,c("model_type", "random","Nparam","WAIC","lppd" ))
  })
