# WARNING - Generated by {fusen} from dev/flat_main.Rmd: do not edit by hand

age <- rnorm(100, 0, 1)
z <- 0.2+ 15 * (1 - exp(-(1) * age)) +rnorm(100, 0, 0.01)
dat = data.frame(age = age, z = z,IND =sample(c(0:20), 100, replace = TRUE)
)

test_that(
  "Gro_ModSettings error",
  {
    expect_error(
      dat %>% Gro_ModSettings(mod = "vonBert"),
      regexp = "The growth models supported are: logistic, gompertz, tpgm, power, richards, vonbertalanffy")
    expect_error(
      dat$z %>% Gro_ModSettings(),
      regexp = "data is not a data frame")
  })



test_that(
  "Gro_ModSettings works",
  {     
    a=dat %>% Gro_ModSettings(mod = "vonbertalanffy")
  expect_named(a,
               c("model_nim","model_fun",  "const_nim",  "data_nim",   "inits_nim",  "parameters", "maxval", 'minval'))
  expect_named(a$inits_nim, c('mu_z0', 'mu_zinf', 'mu_gamma', 'sigma_res'))
  expect_named(a$data_nim, c("z", "age"))
  expect_named(a$const_nim, c("N", "Nind", "IND"))
  }
)
