# WARNING - Generated by {fusen} from dev/flat_main.Rmd: do not edit by hand

Age <- sample(c(0:10), 1000, replace = TRUE)
MeasurementValue <- exp(0.2+15 * (1 - exp(-(0.1) * log(Age+1)))+ rnorm(1000,0,0.01))-1 
AnimalAnonID <- sample(c(0:20), 100, replace = TRUE)
dat = data.frame(Age = Age, MeasurementValue = MeasurementValue, 
                 AnimalAnonID = AnimalAnonID, MeasurementType = "Live Weight")
out = dat %>% Gro_analysis()


test_that(
  "Gro_pred",
  { 
    p<- dat %>% Gro_pred(out$model)
    expect_named(p,c("summary", "predictions", "plot_pred", "posterior", "convergence", "GOF"))
    expect_length(p$plot_pred$layers,3)
   expect_named(p$summary,c("mean", "sd", "QI 2.5", "QI 97.5", "Rhat"))
   expect_named(p$predictions,c("Age", "mean" , "Conf_Int_low", "Conf_Int_up" ))
   expect_named(p$GOF,c("normal", "X", "var" ,"conv"))
   expect_true("ggplot" %in% class(p$posterior))
expect_true("ggplot" %in% class(p$convergence))
})
