# WARNING - Generated by {fusen} from dev/flat_nimble.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("hist_post returns ggplot object",{
  p <- hist_post(rnorm(1000))
  expect_is(p,"ggplot")
  # expect_that(df, equals(p$data))
})

test_that("hist_post uses correct labels & geometry",{
  p <- hist_post(rnorm(1000))
  expect_equal(p$labels$y,"Density")
  expect_equal(class(p$layers[[1]]$geom)[1],"GeomTile")
  expect_equal(class(p$layers[[1]]$stat)[1],"StatIdentity")
})


