# WARNING - Generated by {fusen} from dev/flat_nimble.Rmd: do not edit by hand # nolint: line_length_linter.


test_that("Rhatfun works", {
  rb = array(rnorm(15*3*4), dim = c(15,3,4))
  expect_gte(sum(Rhatfun(rb, nch = 3, it = 15, nparam = 4)),
             0)
  expect_error(Rhatfun(rb, nch = 2, it = 15, nparam = 4))
})
