# WARNING - Generated by {fusen} from dev/flat_nimble.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("conv_plot returns ggplot object",{
  p <- conv_plot(rnorm(1500), m =500)
  expect_is(p,"ggplot")
})

test_that("conv_plot uses correct labels & geometry",{
  p <- conv_plot(rnorm(1000), m =500)
  expect_equal(p$labels$y,"value")
  expect_equal(class(p$layers[[1]]$geom)[1],"GeomLine")
})


