# WARNING - Generated by {fusen} from dev/flat_nimble.Rmd: do not edit by hand


test_that("Rhatfun works", {
  rb = array(rnorm(15*3*4), dim = c(15,3,4))
  expect_gte(sum(Rhatfun(rb, nch = 3, it = 15, nparam = 4)),
             0)
  expect_error(Rhatfun(rb, nch = 2, it = 15, nparam = 4))
})


test_that("sum_nim works", {
  rb = array(rnorm(15*3*4), dim = c(15,3,4))
  expect_equal(sum_nim(rb2 = rb, nch = 3)%>%
                 colnames, c('mean','sd','QI 2.5','QI 97.5','Rhat'))
  expect_equal(sum_nim(rb2 = rb, nch = 3)%>%
                 nrow, 4)
  expect_error(sum_nim(rb2 = rb, nch = 2))
})
