# WARNING - Generated by {fusen} from dev/flat_main.Rmd: do not edit by hand

logx <- rnorm(10000, 0, 1)
id1 =  rnorm(21,0, 0.5)
IND =sample(c(1:20), 100, replace = TRUE)
logz <- 0.2+ id1[IND]+ (15 )* (1 - exp(-(1) * logx)) +rnorm(100, 0, 0.01)
dat = data.frame(logx = logx, logz = logz, IND = as.numeric(factor(IND , labels = c(1:length(unique(IND)))))
)

test_that("Gro_run work", {
  a = Gro_run(1, 
              all_mods  = c("vonbertalanffy", "fabens"),
              dat,random = c("z0"),
              run = list(nit = 1000, nburnin = 100, nthin = 1, nch = 1))
  expect_named(a,c("model","tab"))
  expect_equal(a$model$coef%>%
                 nrow, 900 )
  expect_named(a$tab, c("model_type", "random", "index","Nparam", "WAIC", "lppd"))
})

