# WARNING - Generated by {fusen} from dev/flat_nimble.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot for convergence
#' 
#' Prepare a histogram ggplot for posterior distribution of a given parameter. To be used within codes for plotting grids of posterior distributions of several parameters.
#' 
#' @param x \code{numeric vector} raw estimates of parameters
#' @param m \code{numeric} number of iterations
#'
#' @return plot
#' 
#' @importFrom graphics hist 
#' @importFrom ggplot2 ggplot geom_tile ylab xlab aes
#' @import assertthat
#' 
#' @export
#' @examples
#' conv_plot(rnorm(1500), m =500)
conv_plot<-function(x, m ){
  assert_that(is.numeric(x))
  assert_that(is.numeric(m))
nch = length(x)/m
  data = data.frame(x = x, xline = rep(1:m,nch), chain = as.factor(rep(1:nch,each=m)))
  p=ggplot2::ggplot(data) +
    geom_line(aes(y=x, x = xline,group = chain, color = chain))+
    ylab("value") + xlab("")
  return(p)
}
