# WARNING - Generated by {fusen} from dev/flat_main.Rmd: do not edit by hand

#' Run growth model
#' 
#' Build and run the bayesian growth model `x` of `all_mods`.
#' 
#' @param x \code{numeric} index of the formula used to build the model
#' @param all_mods \code{vector of characters} of model names. The following models are supported: logistic, gompertz, tpgm, power, richards, vonbertalanffy.
#' @param dat \code{data.frame}including at least the numeric columns *age*, *z* and *IND*
#' @param random {vector of character} of the same length as \code{all_mods} giving the parameters that should be included an individual random effect
#' @param run \code{list} Bayesian parameters. They should be increased to reach convergence \itemize{
#' \item \code{nch} number of chains.
#' \item \code{nthin} interval between iterations to keep.
#' \item \code{nburnin} number of iterations to discard.
#' \item \code{nit} total number of iterations.
#' }
#'
#' @return This function returns a \code{list}:
#'         \itemize{
#'           \item \code{model} a list including estimates of coefficients and model characteristics
#'           \item \code{tab} a data frame with information on models & WAIC
#'           }
#' 
#' @import dplyr assertthat nimble
#' @importFrom nimble getNimbleOption
#' 
#' @export
#' @examples
#' age <- rnorm(10000, 0, 1)
#' id1 =  rnorm(21,0, 0.5)
#' id2 =  rnorm(21,0, 0.4)
#' id3 =  rnorm(21,0, 0.3)
#' IND =sample(c(1:20), 100, replace = TRUE)
#' z <- 0.2+ id1[IND]+ (15 + id2[IND])* (1 - exp(-(1+ id3[IND]) * age)) +
#'   rnorm(100, 0, 0.01)
#' dat = data.frame(age = age, z = z, 
#'                  IND = as.numeric(factor(IND ,labels = c(1:length(unique(IND)))))
#' )
#'
#' #Run a vonbertalanffy model including an individual effect on z0
#' out = Gro_run(1, 
#'               dat,
#'               all_mods  = c("vonbertalanffy"),
#'               random = c("z0"),
#'               run = list(nit = 500, nburnin = 100, nthin = 10, nch = 3))
#' out$tab
#'
Gro_run<-function(x, 
                  dat,
                  all_mods,
                  random = "",
                  run = list(nit = 100, nburnin = 10, nthin = 1, nch = 1)){
  
  assert_that(is.numeric(x))
  assert_that(x>0)
  assert_that(is.vector(all_mods))
  assert_that(is.character(all_mods))
  assert_that(x<= length(all_mods))
  assert_that(is.data.frame(dat))
  assert_that(dat %has_name% c('age', 'z', 'IND'))
  assert_that(is.numeric(dat$age))
  assert_that(is.numeric(dat$z))
  assert_that(run %has_name% c("nit", "nburnin", "nthin", "nch"))
  assert_that(is.character(random))
  model_type=all_mods[x]
  random_mod = strsplit(random[x], 
                        paste(c(","," ", ";"), collapse = "|"))%>%
    unlist%>%
    stringi::stri_remove_empty()
  
  model_gro<-Gro_ModSettings(dat, random = random_mod, mod =  model_type)
  
  param = stringr::str_subset(model_gro$parameters, '_', negate = T)
  if(length(random_mod)>1){
    for(r in random_mod){
      assert_that(r %in% param, msg = glue::glue("{r} is not a parameter of the model}"))
    }
  }
  model_nimble = Gro_writenimblecode(params = param, 
                                     model = model_gro$model_nim,
                                     random = random_mod,
                                     maxval = model_gro$maxval, 
                                     minval= model_gro$minval
  )
  outnim <- runnimble(model = model_nimble,
                      const = model_gro$const_nim,
                      data_nim =  model_gro$data_nim,
                      inits_nim = model_gro$inits_nim,
                      param = model_gro$parameters,
                      run = run,
                      model_type = model_type,
                      x = x)


  # outnim=c()
  # outnim$coeff= outnim$WAIC$WAIC = outnim$WAIC$lppd=1
   out=list()
  out$model=list(model_type = model_type,
                 random = random_mod,
                 coef = as.data.frame(outnim$coef),
                 run = run,
                 params = param,
                 model_fun = model_gro$model_fun
  )
  
  out$tab <- data.frame(
    model_type = model_type,
    random = stringr::str_c(random_mod, collapse = ", "),
    index = x,
    Nparam =  (length(model_gro$param)-1),
    WAIC = outnim$WAIC$WAIC,
    lppd = outnim$WAIC$lppd
    
  )
  return(out)
}
