# WARNING - Generated by {fusen} from dev/flat_nimble.Rmd: do not edit by hand

#' Write nimble code for growth model
#' 
#' Write the nimble code needed to run growth model including random effects
#' 
#' @param params \code{vector of character} names of all parameters of the model. 
#' @param model \code{character} likelihood of the nimble model
#' @param random \code{vector of character} name of the parameters that must include an individual random effect
#' @param maxval \code{list} including the maximum values for prior for each parameter. Default value is 1000.
#' @param minval \code{list} including the minimum values for prior for each parameter.Default value is 0.
#'
#' @return A character representing a nimble model
#' 
#' @importFrom glue glue
#' @importFrom stringr str_detect
#' @import assertthat
#' @export
#' @examples
#' #Example for a von bertalanffy model
#' Gro_writenimblecode(params = c('z0', 'zinf', 'gamma'), 
#'                     model = "for (j in 1:N){{
<<<<<<< HEAD
#'        logz[j] ~dnorm(z0[IND[j]] + zinf[IND[j]] * 
#'        (1 - exp(- gamma[IND[j]] * logx[j])), sigma_res)}}",
=======
#'        logz[j] ~dnorm(z0[IND[j]] + zinf[IND[j]] * (1 - exp(- gamma[IND[j]] * logx[j])), sigma_res)}}",
>>>>>>> 477a9e1177176026d2b387122272aa26e641282b
#'                     random = "gamma",
#'                     maxval = list(z0 = 5), 
#'                     minval= list(z0 = 0, zinf = 0, gamma = 0)
#' )

Gro_writenimblecode <- function(params, model,
                                random= c() , 
                                maxval= list() , 
                                minval =list()
                                ) {
  
  
  assert_that(is.character(params))
  if(length(random)>0) {
    assert_that(is.character(random))
  assert_that(all(random %in% params))
  }
  assert_that(is.character(model))
  assert_that(stringr::str_detect(model,"j in 1:N"))
  assert_that(is.list(maxval))
  if(length(maxval)>0) {
    assert_that(all(names(maxval) %in% params))
  }
    assert_that(is.list(minval))
    if(length(minval)>0) {
    assert_that(all(names(minval) %in% params))
    }
    
prior ="sigma_res~ dunif(0, 5)"
  for (p in params){
    assert_that(str_detect(model, p), msg = glue("{p} not included in the likelihood of the model"))
    
      if(!(p %in% names(maxval)) ){maxval[[p]] <-1000}
      if(!(p %in% names(minval)) ){minval[[p]] <-0}
      if(p %in% random){
        prior <- glue("{prior} 
         mu_{p}~ dunif({minval[[p]]}, {maxval[[p]]})
         sigma_{p}~ dunif(0, 5)
         for (i in 1:Nind){{
         {p}[i] ~ dnorm(mu_{p}, sd = sigma_{p}) }}
        ")
        }else{
          prior <- glue("{prior} 
         mu_{p}~ dunif({minval[[p]]}, {maxval[[p]]})
         for (i in 1:Nind){{
         {p}[i] <- mu_{p} }}
        ")
        }
      }
        
  a=glue("
      {prior}
      {model}
      ")
  
  b=parse(text=a)
  return( bquote(.(b)))
}

