# WARNING - Generated by {fusen} from dev/flat_main.Rmd: do not edit by hand # nolint: line_length_linter.


#' Predictions and plots
#' 
#' Give predicted values of the model and plots to check the convergence of the model
#' 
#' @param data \code{data.frame} including at least the numeric columns *Age*, *MeasurementValue* and *AnimalAnonID* 
#' @param out result output from Gro_run()
#' @param Cred_int \code{numeric} lower and upper bound of the credible interval to plot and to predict
#' @param title \code{character} Title of the plot
#' 
#' @import dplyr assertthat 
#' @importFrom ggplot2 ggplot  geom_line ggtitle geom_ribbon aes geom_point
#' @importFrom stringr str_which
#' @importFrom stats lm shapiro.test
#'
#' @return a list including \itemize{
#' \item `summary`shomwing mean, standard deviation, credible interval at 95% and the Gelman-Rubin statistics Rhat of each parameter.
#' \item `predictions` giving the mean estimates and credible interval at 95% of each age
#' \item `GOF`: 4 tests of googness of fit: "normal": test if residuals are normally distributes ; "X"; test if there is a trend between residual and Age, "var": Test if there is the trend in the variance of the residuals over Age ,"conv": check if all Rhat < 1.1
#' \item `plot_pred` Plot of the predicted values, credible interval at 95% in grey and data points.
#' \item `convergence`: Plots of the Bayesian chains 
#' \item `posterior`: Plots of the posterior distribution for each parameter
#' }
#' 
#' @export
#' @examples
#' Age <- sample(c(0:10), 100, replace = TRUE)
#' AnimalAnonID <- sample(c(0:20), 100, replace = TRUE)
#' MeasurementValue <- exp(0.2+15 * (1 - exp(-(0.1) * log(Age+1)))+ 
#'                           rnorm(100,0,0.01) + AnimalAnonID*0.1)-1 
#' dat = data.frame(Age = Age, MeasurementValue = MeasurementValue, 
#'                  AnimalAnonID = AnimalAnonID, MeasurementType = "Live Weight")
#'
#' out = Gro_analysis(dat, 
#'                    all_mods = c("vonbertalanffy"),
#'                    run = list(nit = 1000, nburnin = 100, nthin = 1, nch = 3))
#'
#' p <- Gro_pred(data = dat, 
#'               out = out$model, 
#'               title =out$wAIC_tab$model[1])
#' p$summary
#' p$predictions
#' p$GOF
#' p$plot_pred
#' p$convergence
#' p$posterior
Gro_pred <- function(data, out, Cred_int = c(0.025,0.975),title = "") {
  assert_that(is.data.frame(data))
  assert_that(data %has_name% c("MeasurementValue","Age", 'AnimalAnonID'))
  assert_that(is.numeric(data$MeasurementValue))
  assert_that(is.numeric(data$Age))
  assert_that(is.numeric(Cred_int))
  assert_that(length(Cred_int) == 2)
  assert_that(all(Cred_int<=1))
  assert_that(all(Cred_int>=0))
  assert_that("coef" %in% names(out), msg = "out must be created using function Gro_run or Gro_analysis")
  assert_that("model_fun" %in% names(out), msg = "out must be created using function Gro_run or Gro_analysis")
  
  
  toplot = c(str_which(names(out$coef), "mu"),
             str_which(names(out$coef), "sigma"))
  beta_tt <- out$coef[,toplot]
  
  
  resrb <- sum_nim(as.matrix( beta_tt), out$run$nch)
  
  
  #Plot histograms of beta
  mpl=mconv=list()
  
  for (i in 1:ncol(beta_tt)){
    mpl[[i]] <- hist_post( beta_tt[, i] )
    mconv[[i]] <- conv_plot( beta_tt[, i],  (out$run$nit-out$run$nburnin)/out$run$nthin)
    
  }
  post_pl<- cowplot::plot_grid(plotlist = mpl, 
                               align = "hv", 
                               nrow = ceiling(sqrt(ncol(beta_tt))),
                               ncol = round(sqrt(ncol(beta_tt))),
                               labels = colnames(beta_tt),
                               label_x = 0, label_y = 0, label_size = 12,
                               hjust = -0.5, vjust = -0.5
  )
  conv_pl<- cowplot::plot_grid(plotlist = mconv, 
                               align = "v", 
                               nrow = ncol(beta_tt),
                               labels = colnames(beta_tt),
                               label_x = 0, label_y = 0, label_size = 12,
                               hjust = -0.5, vjust = -0.5
  )
  
  

  
  # Predictions
  #Vector for predictions
  zQuant <- tibble(Age = seq(min(data$Age), max(data$Age)+0.1, 0.1),
                   mean = numeric(1),
                   Conf_Int_low = numeric(1),
                   Conf_Int_up = numeric(1)
  )
  
  #Fitted values and residuals
  for (j in 1:nrow(zQuant)){
      if(out$logtransform){

    pred = out$model_fun(log(zQuant$Age[j]+1),out$coef)
    zQuant$mean[j] = mean(exp(pred)-1)
    zQuant$Conf_Int_low[j] = quantile(exp(pred)-1, Cred_int[1])
    zQuant$Conf_Int_up[j] =  quantile(exp(pred)-1, Cred_int[2])
      }else{
           pred = out$model_fun(zQuant$Age[j],out$coef)
    zQuant$mean[j] = mean(pred)
    zQuant$Conf_Int_low[j] = quantile(pred, Cred_int[1])
    zQuant$Conf_Int_up[j] =  quantile(pred, Cred_int[2])

      }
  }
  
  data_pred = data%>%
    mutate(Age= round(Age,0.1))%>%
    group_by(Age)%>%
    summarize(MeasurementValue = mean(MeasurementValue))%>%
    left_join(zQuant%>%select(Age, mean), by = "Age")
  
   if(out$logtransform){
      data = data%>%
        mutate(Age = log(Age+1),
               mean = log(mean +1),
                MeasurementValue = log(MeasurementValue+1))
  }
  #GOF
  GOF = list(normal = T, X = T, var = T, conv = all(resrb$Rhat<1.1))
  ez <- data_pred$MeasurementValue - data_pred$mean
  ez2 <- ez^2
  test  = shapiro.test(ez)
  if(test$p.value<0.01){GOF$normal = FALSE}
  a = summary(lm(ez2 ~ data_pred$Age)) #test variance?
  if(a$coefficients[2,4]<0.01){GOF$X = FALSE}
  b = summary(lm(ez ~ data_pred$Age)) #test pour senescence??
  if(b$coefficients[2,4]<0.01){GOF$var = FALSE}
  
  
  
  p <- ggplot(data, aes(x = Age))+
    ggtitle(title)+
    geom_point(aes(y = MeasurementValue))+
    geom_ribbon(data = zQuant,aes ( ymin = Conf_Int_low, ymax = Conf_Int_up),
                fill = "grey80", alpha = 0.25)+
    geom_line(data = zQuant,aes ( y = mean ))
  
  
  
  return(list(summary =  resrb, 
              predictions=zQuant,
              plot_pred = p, 
              posterior =post_pl, 
              convergence = conv_pl, 
              GOF = GOF ))
}
