# WARNING - Generated by {fusen} from dev/flat_nimble.Rmd: do not edit by hand

#' Histogram
#' 
#' Prepare a histogram ggplot for posterior distribution of a given parameter. To be used within codes for plotting grids of posterior distributions of several parameters.
#' 
#' @param x \code{numeric vector} raw estimates of parameters
#' @param namex \code{character} x axis label
#' @param namelab \code{character} title label of the plot
#'
#' @return histogram plot
#' 
#' @importFrom graphics hist 
#' @importFrom ggplot2 ggplot geom_tile ylab xlab aes
#' @import assertthat
#' 
#' @export
#' @examples
#' hist_post(rnorm(1000))
hist_post<-function(x, namex = "", namelab = ""){
  assert_that(is.numeric(x))
  assert_that(is.vector(x))
  nom = eval(namelab)
  ggplot2::ggplot() +
    geom_tile(data = data.frame(x = hist(x,plot = FALSE)$mids, 
                                y = hist(x,plot = FALSE)$density),
              aes(x=x,y=y/2,height = y),
              width = diff(hist(x,plot = FALSE)$mids[c(1,2)]), 
              fill = "midnightblue", color = "white") +
    ggpp::geom_text_npc(aes(npcx = "right", npcy ="top", label= nom ,size=3.5))+
    ylab("Density") + xlab(namex)
}
