# WARNING - Generated by {fusen} from dev/flat_nimble.Rmd: do not edit by hand # nolint: line_length_linter.

#' Summary statistics
#' 
#' Makes a summary table with main statistics for each parameter from output chains of a Bayesian model
#' 
#' @param rb2 \code{array} of dimension 3 or 2 including estimates of output chains of a bayesian model. If of dimension 3, the rows should be the iterations, the columns the different chains and the 3rd dimension the parameters. If of dimension 2, the rows should be the iterations and chains, and the columns the parameters.
#' @param nch \code{numeric} number of chains
#'
#' @return A summary matrix with columns giving mean, sd, credible interval at 2.5% and 97.5%, and Rubin Gelman Rhat statistic. The different parameters are on lines. 
#' 
#' @import assertthat
#' @importFrom stats sd quantile median 
#' 
#' @export
#' @examples
#' rb = array(rnorm(15*3*4), dim = c(15,3,4))
#' sum_nim(rb, nch = 3)
#'
sum_nim<-function(rb2, nch){
  
  assert_that(is.numeric(nch))
  assert_that(is.array(rb2))
  
  if(length(dim(rb2))!=3 & length(dim(rb2))!=2){stop("rb2 should be of dimension 3 or 2")}
  
  if(length(dim(rb2))==2){
    rb =rb2
    m=dim(rb)[1]/nch
    rb2 = array(NA, dim = c(m, nch, dim(rb)[2]))
    for (i in 1:nch){rb2[,i,] = rb[(i-1)*m+(1:m),]}
    dimnames(rb2)[[3]] = colnames(rb)
  }   
  m=dim(rb2)[1]
  assert_that(nch == dim(rb2)[2])
  long=dim(rb2)[3]
  sumres=matrix(NA,nrow=dim(rb2)[3],ncol=5)
  rownames(sumres)=dimnames(rb2)[[3]]
  colnames(sumres)=c('mean','sd','QI 2.5','QI 97.5','Rhat')
  sumres[,1]=   apply(rb2,3, mean)
  sumres[,2]=   apply(rb2,3, sd)
  sumres[,3]=   apply(rb2,3, quantile,0.025)
  sumres[,4]=   apply(rb2,3,quantile,0.975)
  if(nch> 1) {
    sumres[,5]=   Rhatfun(rb2,nch,m,long)}
  
  
  return(as.data.frame(sumres))
}

